# Generated by Django 5.2.7 on 2026-01-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("adoption_request", "Adoption Request"),
                    ("adoption_approved", "Adoption Approved"),
                    ("adoption_rejected", "Adoption Rejected"),
                    ("pet_approved", "Pet Approved"),
                    ("pet_rejected", "Pet Rejected"),
                    ("vaccination_due", "Vaccination Due"),
                    ("vaccination_administered", "Vaccination Administered"),
                    ("care_reminder", "Care Reminder"),
                    ("general", "General"),
                ],
                max_length=30,
            ),
        ),
    ]
