# Generated by Django 6.0.2 on 2026-03-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptionrequest",
            name="is_reapplication",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adoptionrequest",
            name="reapplication_count",
            field=models.IntegerField(default=0),
        ),
    ]
